[profile.default]
src = 'contracts'
out = 'forge/out'
cache_path = 'forge/cache'
libs = ['node_modules', 'lib']
test = 'test/foundry'
# compilers config
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 1000
build_info = true
gas_limit = 1_000_000_000
extra_output = ["storageLayout"]

[fmt]
# formatter config
line_width = 100

[fuzz]
runs = 256

[invariant]
runs = 30
depth = 15
fail_on_revert = true
dictionary_weight = 80